package com.materials.shared.action;

public enum GeneralCommand {
	READ_MENUS_SLIDERS_ARTICLES_RSOCIAUX_WEBSITE, SEND_MAIL, LOGIN, LOGOUT, CHECK_LOGIN, RESET_PWD, DELETE_TEMPFILE, SAVE_SITE, INCREMENT_CONTENT_VIEW, RESET_PWD_CODE

}
