package com.materials.shared.action.content;

public enum ContentCommand {

	BY_MENU_NAME, BY_SLIDER_ID, ALL_ARTICLE_CONTENTS, FOR_HOME_ACTIVE, BY_TITEL, FAVORITS, ALL_ANNONCES_FOR_USER, ALL_CONTENTS_LABEL, ALL_ANNONCES_BY_CATEGORY, ANNONCES_BY_PAGE_NR
}
