package com.materials.shared.action.stats;

public enum StatisticCommand {
	STATISTIC_BY_LABEL, ALL_ACTIVE_STATISTICS, ALL_STATISTICS, ALL_STATITEMS_BY_USER, ALL_STATITEMS_BY_STATISTIC,STATITEM_BY_USER_AND_STATISTIC;
}
